trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
    clean: all

variables:
  buildConfiguration: 'release'

pool:
  name: 'DAS - Continuous Integration'
  demands: Agent.OS -equals Linux

steps:
- task: gittools.gitversion-preview.gitversion-task.GitVersion@5
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '- task: PublishHtmlReport@1
  inputs:
    reportDir: '$(build.artifactstagingdirectory)/TestReports'/publish'
